__________________________________________________________________________________________________
RecurDyn V9R5 [Windows x64 System 9.5.10442.0] Analysis message file.
Copyright (C) 1997 - 2021 FunctionBay, Inc. All rights reserved.

Model file: WOR_01\WOR.rdyn [Model Name: WOR]

_________________________________________________________________________________________________
System Configuration Information
    No. of Generalized Coordinate                   = 8
    No. of Generalized Velocity                     = 8
    No. of Rigid Body                               = 9

Kinematic Degree of Freedom         = 8

Total array size                    = 14222
Total memory size for array         = 0 MB

Success Process: Array Structure Construction

_________________________________________________________________________________________________
Redundant Constraint Information
    There is no redundant constraint

_________________________________________________________________________________________________
RecurDyn/SOLVER Information
    DLL type Solver for Windows 64 Bit
    No. of CPU Thread = 4
    Save Solver Animation File(RAN) Option is turned on
    C:\Program Files\FunctionBay, Inc\RecurDyn V9R5\Bin\Solver\Slvcore.dll
    C:\Program Files\FunctionBay, Inc\RecurDyn V9R5\Bin\Solver\Cuser.dll

_________________________________________________________________________________________________
Analysis Information
    Dynamic Analysis
    End Time                       = 2.000000000000000
    Step                           = 2000
    Plot Multiplier Step Factor    = 1
    Maximum Time Step              = 1.0E-02
    Initial Time Step              = 1.0E-06
    Error Tolerance                = 5.0E-03

_________________________________________________________________________________________________
Integrator Information
     Advanced Hybrid Implicit Integrator
        Numerical Damping          = 1.000000
        Linear Solver For MBD      = DENSE

_________________________________________________________________________________________________
Information of starting time
    Starting Time/Date     = 18:34:39 / 2026.4.13

_________________________________________________________________________________________________
Analysis processing...

        TIME          STEPSIZE        A_DELNRM          NJAC      NRES      ANRF     AINTF
    6.133000E-03    5.120000E-04    4.586941E-08         100       300         0         0
    6.302130E-01    1.000000E-02    4.797356E-01         201       622         0         0
    1.552029E+00    6.345863E-03    4.401956E-01         343      1184         0         0
    2.000000E+00    1.594620E-03    3.303323E-03         427      1533         0         0

_________________________________________________________________________________________________
Analysis Time Information
    Starting Time/Date     = 18:34:39 / 2026.4.13
    Ending Time/Date       = 18:34:39 / 2026.4.13
    CPU Time = 0.25 Second (0 hr. 0 min 0.25 sec.)

_________________________________________________________________________________________________
Analysis is accomplished successfully

_________________________________________________________________________________________________
