__________________________________________________________________________________________________
RecurDyn V9R5 [Windows x64 System 9.5.10442.0] Analysis message file.
Copyright (C) 1997 - 2021 FunctionBay, Inc. All rights reserved.

Model file: WOR_27\WOR.rdyn [Model Name: WOR]
_________________________________________________________________________________________________
Warning has occurred
[C0358][Scenario][Command] WARNING: The Maximum Time Step (0.010000) is greater than Report Time Step (0.001000). The Maximum Time Step is set (0.001000).

_________________________________________________________________________________________________
System Configuration Information
    No. of Generalized Coordinate                   = 8
    No. of Generalized Velocity                     = 8
    No. of Rigid Body                               = 9

Kinematic Degree of Freedom         = 4

Total array size                    = 15844
Total memory size for array         = 0 MB

Success Process: Array Structure Construction

_________________________________________________________________________________________________
Redundant Constraint Information
    There is no redundant constraint

_________________________________________________________________________________________________
RecurDyn/SOLVER Information
    DLL type Solver for Windows 64 Bit
    No. of CPU Thread = 4
    Save Solver Animation File(RAN) Option is turned on
    C:\Program Files\FunctionBay, Inc\RecurDyn V9R5\Bin\Solver\Slvcore.dll
    C:\Program Files\FunctionBay, Inc\RecurDyn V9R5\Bin\Solver\Cuser.dll

_________________________________________________________________________________________________
Analysis Information
    Dynamic Analysis
    End Time                       = 2.000000000000000
    Step                           = 2000
    Plot Multiplier Step Factor    = 1
    Maximum Time Step              = 1.0E-02
    Initial Time Step              = 1.0E-06
    Error Tolerance                = 5.0E-03

_________________________________________________________________________________________________
Integrator Information
     Advanced Hybrid Implicit Integrator
        Numerical Damping          = 1.000000
        Linear Solver For MBD      = DENSE

_________________________________________________________________________________________________
Information of starting time
    Starting Time/Date     = 15:8:58 / 2026.4.14

_________________________________________________________________________________________________
Analysis processing...

        TIME          STEPSIZE        A_DELNRM          NJAC      NRES      ANRF     AINTF
    1.600000E-02    1.000000E-03    1.220162E-06         100       300         0         0
    1.150000E-01    1.000000E-03    1.305314E-05         199       597         0         0
    2.140000E-01    1.000000E-03    3.117333E-05         298       894         0         0
    3.130000E-01    1.000000E-03    1.732138E-05         397      1191         0         0
    4.120000E-01    1.000000E-03    9.833479E-06         496      1488         0         0
    5.110000E-01    1.000000E-03    4.416677E-05         595      1785         0         0
    6.100000E-01    1.000000E-03    4.618489E-04         694      2082         0         0
    7.090000E-01    1.000000E-03    4.285797E-04         793      2379         0         0
    8.080000E-01    1.000000E-03    2.220292E-04         892      2676         0         0
    9.070000E-01    1.000000E-03    1.516475E-04         991      2973         0         0
    1.006000E+00    1.000000E-03    6.215906E-05        1090      3270         0         0
    1.105000E+00    1.000000E-03    9.063564E-05        1189      3567         0         0
    1.204000E+00    1.000000E-03    2.982066E-04        1288      3864         0         0
    1.303000E+00    1.000000E-03    2.025247E-03        1387      4161         0         0
    1.402000E+00    1.000000E-03    6.759153E-04        1486      4458         0         0
    1.501000E+00    1.000000E-03    3.474795E-04        1585      4755         0         0
    1.600000E+00    1.000000E-03    3.844866E-04        1684      5052         0         0
    1.699000E+00    1.000000E-03    1.181001E-04        1783      5349         0         0
    1.798000E+00    1.000000E-03    7.392052E-03        1882      5646         0         0
    1.897000E+00    1.000000E-03    1.342853E-04        1981      5943         0         0
    1.996000E+00    1.000000E-03    2.322374E-05        2080      6240         0         0
    2.000000E+00    1.000000E-03    3.887507E-05        2084      6252         0         0

_________________________________________________________________________________________________
Analysis Time Information
    Starting Time/Date     = 15:8:58 / 2026.4.14
    Ending Time/Date       = 15:8:58 / 2026.4.14
    CPU Time = 0.58 Second (0 hr. 0 min 0.58 sec.)

_________________________________________________________________________________________________
Analysis is accomplished successfully

_________________________________________________________________________________________________
